version: "3.9"
services:
  crud:
    restart:
      'always'
    container_name: 'orders'
    build:
      dockerfile: 'deploy/Dockerfile'
      context: '../.'
    volumes:
      - '../.:/go/src/app/server'
    ports:
      - '3300:3300'
    environment:
      - JETSTREAM_URL=jetstream:4222
      - PG_ADDRESS=postgres:5432
    depends_on:
        - postgres
        - jetstream
  init:
    build:
      dockerfile: 'deploy/Dockerfile-init'
      context: '../.'
    environment:
      - NATS_URL=jetstream:4222
    volumes:
      - '../.:/go/src/app/server'
    depends_on:
      - jetstream
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "natsDB"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ../sql:/docker-entrypoint-initdb.d
      - .:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: [ 'CMD-SHELL', 'psql -h localhost -U $${POSTGRES_USER} -c select 1 -d $${POSTGRES_DB}' ]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
  jetstream:
    image: nats:2.9-alpine
    command: --js --sd /data -p 4222 -m 8222
    ports:
    - 4223:4222
    - 8223:8222
    volumes:
    - ./jetstream-data:/data
    